server:
  port: 8200
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service

---
spring:
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
    config:
      fail-fast: true #클라이언트 서버를 시작할 때 Config 서버에서 정보를 로드할 수 없을 경우에는 서버를 실행하지 않겠다는 설정
      name: msaConfigFileDev

---
# actuator를 이용하여 서버 재시작 없이 변경내용 반영 가능하게 함.
management:
  endpoints:
    web:
      exposure:
        include: refresh

---
token:
  access-expired-time: 3333333
  refresh-expired-time: 4444444
  secret: s1kfktAkfTkal4Ebdrbrdpekfadktjfhtkaktel3dks9lgkfTpdlfjswjscifhghfQodltu7eh

kafka:
  consumer:
    group-id: first-group
  bootstrap-servers: 127.0.0.1:9092

---
spring:
  redis:
    database: 0
    port: 6379
    host: 172.17.0.1
    password: fpeltm12!

---
spring:
  redis:
    pool:
      max:
        total: 60
        idle: 60
      min:
        idle: 10
    max:
      wait:
        milli: 2000
