server:
  port: 8200
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jandb
    driver-class-name: org.mariadb.jdbc.Driver
    username: jandb
    password: jandb
  config:
    import: "optional:configserver:"

logging:
  config: classpath:log/logback-spring.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

token:
  access-expired-time: 1800000
  refresh-expired-time: 3600000
  secret: s1kfktAkfTkal4Ebdrbrdpekfadktjfhtkaktel3dks9lgkfTpdlfjswjscifhghfQodltu7eh

cust.security:
  ignore:
    path:
      - /favicon.ico
      - /error
    resource:
      - exe